### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by chronoss09** [ONElua/Easy-Power-Refresh#1]
It's not an issues but, i want to add some feature in this app  and i need a source code for the eboot, is it possible to get it ?

**Comment by chronoss09** [comment]
This is my mod and i want to implant a USB connexion. So, give me just a eboot with USB connexion and the code to actived it if possible...

<a href="https://gyazo.com/d857cacf1ac0872d17c907bf896c35a0"><img src="https://i.gyazo.com/d857cacf1ac0872d17c907bf896c35a0.png" alt="https://gyazo.com/d857cacf1ac0872d17c907bf896c35a0" width="872"/></a>

**Comment by ONElua** [comment]
ahh ok
Send me DM in twitter...

**Comment by chronoss09** [comment]
Ok !
